# Generated by Django 4.2.4 on 2023-10-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
