# Generated by Django 4.2.4 on 2023-10-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_products_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-date_time',)},
        ),
    ]
